class StringAssignment{
	public static void main(String[] args){
		
		String MyName="Bharath";
		System.out.println(MyName);
		String apple = "Apple";
        String banana = "Banana";
        String cherry = "Cherry";
        String date = "Date";
        String elderberry = "Elderberry";
        String fig = "Fig";
        String grape = "Grape";
        String honeydew = "Honeydew";
        String indianFig = "Indian Fig";
        String jackfruit = "Jackfruit";
        String kiwi = "Kiwi";
        String lemon = "Lemon";
        String mango = "Mango";
        String nectarine = "Nectarine";
        String orange = "Orange";
        String papaya = "Papaya";
        String quince = "Quince";
        String raspberry = "Raspberry";
        String strawberry = "Strawberry";
        String tangerine = "Tangerine";
        String ugliFruit = "Ugli Fruit";
        String vanillaBean = "Vanilla Bean";
        String watermelon = "Watermelon";
        String xigua = "Xigua";
        String yellowPassionFruit = "Yellow Passion Fruit";
        String zucchini = "Zucchini";
        String acaiBerry = "Acai Berry";
        String blackberry = "Blackberry";
        String cantaloupe = "Cantaloupe";
        String dragonfruit = "Dragonfruit";
        String eggplant = "Eggplant";
        String feijoa = "Feijoa";
        String gooseberry = "Gooseberry";
        String huckleberry = "Huckleberry";
        String ilama = "Ilama";
        String jambul = "Jambul";
        String kumquat = "Kumquat";
        String lychee = "Lychee";
        String mulberry = "Mulberry";
        String nance = "Nance";
        String olive = "Olive";
        String peach = "Peach";
        String quararibea = "Quararibea";
        String rambutan = "Rambutan";
        String soursop = "Soursop";
        String tamarind = "Tamarind";
        String uvaUrsi = "Uva Ursi";
        String voavanga = "Voavanga";
        String wolfberry = "Wolfberry";
        String ximenia = "Ximenia";
        String yumberry = "Yumberry";
        String ziziphus = "Ziziphus";
        String atemoya = "Atemoya";
        String bilberry = "Bilberry";
        String currant = "Currant";
        String durian = "Durian";
        String elderberryAgain = "Elderberry Again";
        String fingerLime = "Finger Lime";
        String guava = "Guava";
        String hackberry = "Hackberry";
        String imbu = "Imbu";
        String jujube = "Jujube";
        String kiwano = "Kiwano";
        String longan = "Longan";
        String mameySapote = "Mamey Sapote";
        String naranjilla = "Naranjilla";
        String ogeecheeLimes = "Ogeechee Limes";
        String pineapple = "Pineapple";
        String quandong = "Quandong";
        String roseApple = "Rose Apple";
        String santol = "Santol";
        String tangelo = "Tangelo";
        String umbu = "Umbu";
        String velvetApple = "Velvet Apple";
        String whiteSapote = "White Sapote";
		
		System.out.println(apple);
        System.out.println(banana);
        System.out.println(cherry);
        System.out.println(date);
        System.out.println(elderberry);
        System.out.println(fig);
        System.out.println(grape);
        System.out.println(honeydew);
        System.out.println(indianFig);
        System.out.println(jackfruit);
        System.out.println(kiwi);
        System.out.println(lemon);
        System.out.println(mango);
        System.out.println(nectarine);
        System.out.println(orange);
        System.out.println(papaya);
        System.out.println(quince);
        System.out.println(raspberry);
        System.out.println(strawberry);
        System.out.println(tangerine);
        System.out.println(ugliFruit);
        System.out.println(vanillaBean);
        System.out.println(watermelon);
        System.out.println(xigua);
        System.out.println(yellowPassionFruit);
        System.out.println(zucchini);
        System.out.println(acaiBerry);
        System.out.println(blackberry);
        System.out.println(cantaloupe);
        System.out.println(dragonfruit);
        System.out.println(eggplant);
        System.out.println(feijoa);
        System.out.println(gooseberry);
        System.out.println(huckleberry);
        System.out.println(ilama);
        System.out.println(jambul);
        System.out.println(kumquat);
        System.out.println(lychee);
        System.out.println(mulberry);
        System.out.println(nance);
        System.out.println(olive);
        System.out.println(peach);
        System.out.println(quararibea);
        System.out.println(rambutan);
        System.out.println(soursop);
        System.out.println(tamarind);
        System.out.println(uvaUrsi);
        System.out.println(voavanga);
        System.out.println(wolfberry);
        System.out.println(ximenia);
        System.out.println(yumberry);
        System.out.println(ziziphus);
        System.out.println(atemoya);
        System.out.println(bilberry);
        System.out.println(currant);
        System.out.println(durian);
        System.out.println(elderberryAgain);
        System.out.println(fingerLime);
        System.out.println(guava);
        System.out.println(hackberry);
        System.out.println(imbu);
        System.out.println(jujube);
        System.out.println(kiwano);
        System.out.println(longan);
        System.out.println(mameySapote);
        System.out.println(naranjilla);
        System.out.println(ogeecheeLimes);
        System.out.println(pineapple);
        System.out.println(quandong);
        System.out.println(roseApple);
        System.out.println(santol);
        System.out.println(tangelo);
        System.out.println(umbu);
        System.out.println(velvetApple);
        System.out.println(whiteSapote);
		
	}
}